require 'rubygems'
require 'bundler/setup'
require './foo.rb'

desc "precompile"
task :precompile do
  # print "precompiling..."
  foo = Foo.new
  foo.precompile
end

desc "clobber"
task :clobber do
  foo = Foo.new
  foo.clobber
  `rm -rf ./tmp`
end